django_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.common.views import update_profile, login_user, face_login
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('', login_user, name='login'),
    path('face_login', face_login, name='face_login'),

    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', update_profile, name='register'),

    path('time_table/', include('time_table.urls'), name='time_table'),

    path('admin/', admin.site.urls),
]

time_table/urls.py
from django.urls import path

from time_table import views

app_name = 'time_table'

urlpatterns = [
    path('', views.setting, name='setting'),
    path('add_face', views.add_face, name="add_face"),
    path('camera', views.detectme, name='camera'),
]

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/setting.html
<!doctype html>
<html lang="en">

<body>
    <div>
    <!--사용자 사진 등록-->
      <form method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <button type="submit" id="logout">로그아웃</button>
      </form>
      <h3>
          사용자 사진 등록하기
      </h3>
      <div>
          <form method="post" action="{% url 'time_table:add_face' %}">
              <table>
                  <tr>
                      <td width="50%">
                          <img src="http://127.0.0.1:8000/time_table/camera" style="width:200px;"/>
                      </td>
                  </tr>
              </table>
              {% csrf_token %}
              <button type="submit">등록하기</button>
          </form>
      </div>
    </div>
</body>

</html>